"""Remove tenant_id from user

Revision ID: 32ecb8c55196
Revises: f859cc4b64ca
Create Date: 2026-08-11 18:23:35.901029+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32ecb8c55196"
down_revision: str | None = "f859cc4b64ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_identity_users_tenant_id"), table_name="identity_users")
    op.drop_column("identity_users", "tenant_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "identity_users",
        sa.Column("tenant_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("ix_identity_users_tenant_id"), "identity_users", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###
