"""Add workflow models

Revision ID: 3a87817023ff
Revises: 1f9fff817df5
Create Date: 2026-08-12 03:16:13.685124+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3a87817023ff"
down_revision: str | None = "1f9fff817df5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_definitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="workflowdefinitionstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_definitions_organization_id"),
        "workflow_definitions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "workflow_states",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_definition_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column(
            "type", sa.Enum("INITIAL", "NORMAL", "FINAL", name="workflowstatetype"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workflow_definition_id"], ["workflow_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_states_workflow_definition_id"),
        "workflow_states",
        ["workflow_definition_id"],
        unique=False,
    )
    op.create_table(
        "workflow_instances",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("workflow_definition_id", sa.String(length=36), nullable=False),
        sa.Column("current_state_id", sa.String(length=36), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("started_by", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "CANCELLED", name="workflowinstancestatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["current_state_id"],
            ["workflow_states.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workflow_definition_id"], ["workflow_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_instances_organization_id"),
        "workflow_instances",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_instances_resource_id"),
        "workflow_instances",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_instances_resource_type"),
        "workflow_instances",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_instances_workflow_definition_id"),
        "workflow_instances",
        ["workflow_definition_id"],
        unique=False,
    )
    op.create_table(
        "workflow_transitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_definition_id", sa.String(length=36), nullable=False),
        sa.Column("from_state_id", sa.String(length=36), nullable=False),
        sa.Column("to_state_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("required_permission", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["from_state_id"], ["workflow_states.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_state_id"], ["workflow_states.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workflow_definition_id"], ["workflow_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_transitions_workflow_definition_id"),
        "workflow_transitions",
        ["workflow_definition_id"],
        unique=False,
    )
    op.create_table(
        "workflow_executions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_instance_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("from_state", sa.String(length=100), nullable=True),
        sa.Column("to_state", sa.String(length=100), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workflow_instance_id"], ["workflow_instances.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_executions_workflow_instance_id"),
        "workflow_executions",
        ["workflow_instance_id"],
        unique=False,
    )
    op.create_table(
        "workflow_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_instance_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("assigned_user_id", sa.String(length=36), nullable=True),
        sa.Column("assigned_role_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status", sa.Enum("PENDING", "COMPLETED", name="workflowtaskstatus"), nullable=False
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assigned_role_id"], ["roles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["assigned_user_id"], ["identity_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workflow_instance_id"], ["workflow_instances.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_tasks_assigned_role_id"),
        "workflow_tasks",
        ["assigned_role_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_tasks_assigned_user_id"),
        "workflow_tasks",
        ["assigned_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_tasks_workflow_instance_id"),
        "workflow_tasks",
        ["workflow_instance_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_tasks_workflow_instance_id"), table_name="workflow_tasks")
    op.drop_index(op.f("ix_workflow_tasks_assigned_user_id"), table_name="workflow_tasks")
    op.drop_index(op.f("ix_workflow_tasks_assigned_role_id"), table_name="workflow_tasks")
    op.drop_table("workflow_tasks")
    op.drop_index(
        op.f("ix_workflow_executions_workflow_instance_id"), table_name="workflow_executions"
    )
    op.drop_table("workflow_executions")
    op.drop_index(
        op.f("ix_workflow_transitions_workflow_definition_id"), table_name="workflow_transitions"
    )
    op.drop_table("workflow_transitions")
    op.drop_index(
        op.f("ix_workflow_instances_workflow_definition_id"), table_name="workflow_instances"
    )
    op.drop_index(op.f("ix_workflow_instances_resource_type"), table_name="workflow_instances")
    op.drop_index(op.f("ix_workflow_instances_resource_id"), table_name="workflow_instances")
    op.drop_index(op.f("ix_workflow_instances_organization_id"), table_name="workflow_instances")
    op.drop_table("workflow_instances")
    op.drop_index(op.f("ix_workflow_states_workflow_definition_id"), table_name="workflow_states")
    op.drop_table("workflow_states")
    op.drop_index(
        op.f("ix_workflow_definitions_organization_id"), table_name="workflow_definitions"
    )
    op.drop_table("workflow_definitions")
    # ### end Alembic commands ###
