"""Add Audit model

Revision ID: 1f9fff817df5
Revises: 3a99a1af9ed4
Create Date: 2026-08-12 02:59:08.012739+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1f9fff817df5"
down_revision: str | None = "3a99a1af9ed4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_records",
        sa.Column("organization_id", sa.String(length=36), nullable=True),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_records_action"), "audit_records", ["action"], unique=False)
    op.create_index(op.f("ix_audit_records_actor_id"), "audit_records", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_audit_records_organization_id"), "audit_records", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_resource_id"), "audit_records", ["resource_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_resource_type"), "audit_records", ["resource_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_timestamp"), "audit_records", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_records_timestamp"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_resource_type"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_resource_id"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_organization_id"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_actor_id"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_action"), table_name="audit_records")
    op.drop_table("audit_records")
    # ### end Alembic commands ###
