/**
 * @curos/types — Auto-generated TypeScript types from Cortex OI OpenAPI spec.
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY.
 *
 * Regenerate with:
 *   pnpm --filter @curos/types generate
 *
 * This requires cortex-api running on localhost:8000.
 *
 * Alternatively, to generate from a saved spec file:
 *   pnpm --filter @curos/types generate:file
 *   (requires openapi.json in packages/types/)
 *
 * Last generated: placeholder (run generate to populate)
 */

// This file will be populated after running: pnpm --filter @curos/types generate
export type {};
