/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 if the application process is running.
         */
        get: operations["health_liveness_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 when the service is ready to accept traffic (DB + Redis connected).
         */
        get: operations["health_readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Register a new user account.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login and get tokens
         * @description Authenticate a user and return access/refresh tokens.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Get a new access token using a refresh token.
         */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Get the profile of the currently authenticated user.
         */
        get: operations["get_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Organization
         * @description Create a new organization and make the user a member.
         */
        post: operations["create_organization_api_v1_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Organizations
         * @description List organizations the current user is a member of.
         */
        get: operations["list_my_organizations_api_v1_organizations_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Organization
         * @description Get organization details (requires membership).
         */
        get: operations["get_organization_api_v1_organizations__org_id__get"];
        /**
         * Update Organization
         * @description Update organization details (requires membership).
         */
        put: operations["update_organization_api_v1_organizations__org_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Organization Members
         * @description List all members of an organization (requires membership).
         */
        get: operations["list_organization_members_api_v1_organizations__org_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/campuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Campuses
         * @description List campuses for an organization (requires membership).
         */
        get: operations["list_campuses_api_v1_organizations__org_id__campuses_get"];
        put?: never;
        /**
         * Create Campus
         * @description Create a campus within an organization (requires membership).
         */
        post: operations["create_campus_api_v1_organizations__org_id__campuses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Departments
         * @description List departments for an organization (requires membership).
         */
        get: operations["list_departments_api_v1_organizations__org_id__departments_get"];
        put?: never;
        /**
         * Create Department
         * @description Create a department within an organization (requires membership).
         */
        post: operations["create_department_api_v1_organizations__org_id__departments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Roles
         * @description List all roles in an organization. (Requires role.read)
         */
        get: operations["list_roles_api_v1_organizations__organization_id__roles_get"];
        put?: never;
        /**
         * Create Role
         * @description Create a custom role within an organization. (Requires role.manage)
         */
        post: operations["create_role_api_v1_organizations__organization_id__roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/members/{member_user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Role
         * @description Assign a role to an organization member. (Requires member.manage)
         */
        post: operations["assign_role_api_v1_organizations__organization_id__members__member_user_id__role_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Logs
         * @description Get audit logs for an organization.
         *     Requires 'audit.read' permission.
         */
        get: operations["get_audit_logs_api_v1_organizations__organization_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/workflows/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflow Definitions */
        get: operations["list_workflow_definitions_api_v1_organizations__organization_id__workflows_definitions_get"];
        put?: never;
        /** Create Workflow Definition */
        post: operations["create_workflow_definition_api_v1_organizations__organization_id__workflows_definitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/workflows/definitions/{definition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow Definition */
        get: operations["get_workflow_definition_api_v1_organizations__organization_id__workflows_definitions__definition_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/workflows/definitions/{definition_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Workflow Definition */
        post: operations["publish_workflow_definition_api_v1_organizations__organization_id__workflows_definitions__definition_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/workflows/definitions/{definition_id}/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflow States */
        get: operations["list_workflow_states_api_v1_organizations__organization_id__workflows_definitions__definition_id__states_get"];
        put?: never;
        /** Add Workflow State */
        post: operations["add_workflow_state_api_v1_organizations__organization_id__workflows_definitions__definition_id__states_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/workflows/definitions/{definition_id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflow Transitions */
        get: operations["list_workflow_transitions_api_v1_organizations__organization_id__workflows_definitions__definition_id__transitions_get"];
        put?: never;
        /** Add Workflow Transition */
        post: operations["add_workflow_transition_api_v1_organizations__organization_id__workflows_definitions__definition_id__transitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/workflows/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Workflow Instance */
        post: operations["start_workflow_instance_api_v1_organizations__organization_id__workflows_instances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/workflows/instances/{instance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow Instance */
        get: operations["get_workflow_instance_api_v1_organizations__organization_id__workflows_instances__instance_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/workflows/instances/{instance_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Workflow Transition */
        post: operations["execute_workflow_transition_api_v1_organizations__organization_id__workflows_instances__instance_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/workflows/instances/{instance_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow Execution History */
        get: operations["get_workflow_execution_history_api_v1_organizations__organization_id__workflows_instances__instance_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/workflows/instances/{instance_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflow Tasks */
        get: operations["list_workflow_tasks_api_v1_organizations__organization_id__workflows_instances__instance_id__tasks_get"];
        put?: never;
        /** Create Workflow Task */
        post: operations["create_workflow_task_api_v1_organizations__organization_id__workflows_instances__instance_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/workflows/instances/{instance_id}/tasks/{task_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Workflow Task */
        post: operations["complete_workflow_task_api_v1_organizations__organization_id__workflows_instances__instance_id__tasks__task_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_organizations__organization_id__events_get"];
        put?: never;
        /** Create Event */
        post: operations["create_event_api_v1_organizations__organization_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_v1_organizations__organization_id__events__event_id__get"];
        /** Update Event */
        put: operations["update_event_api_v1_organizations__organization_id__events__event_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/events/{event_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Event */
        post: operations["submit_event_api_v1_organizations__organization_id__events__event_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/events/{event_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Event */
        post: operations["approve_event_api_v1_organizations__organization_id__events__event_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/events/{event_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Event */
        post: operations["reject_event_api_v1_organizations__organization_id__events__event_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/events/{event_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Event */
        post: operations["publish_event_api_v1_organizations__organization_id__events__event_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/events/{event_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Event */
        post: operations["start_event_api_v1_organizations__organization_id__events__event_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/events/{event_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Event */
        post: operations["complete_event_api_v1_organizations__organization_id__events__event_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/events/{event_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Event */
        post: operations["archive_event_api_v1_organizations__organization_id__events__event_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/events/{event_id}/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Event */
        post: operations["register_event_api_v1_organizations__organization_id__events__event_id__register_post"];
        /** Cancel Registration */
        delete: operations["cancel_registration_api_v1_organizations__organization_id__events__event_id__register_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/events/{event_id}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Registrations */
        get: operations["list_registrations_api_v1_organizations__organization_id__events__event_id__registrations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/events/{event_id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attendance */
        get: operations["list_attendance_api_v1_organizations__organization_id__events__event_id__attendance_get"];
        put?: never;
        /** Record Attendance */
        post: operations["record_attendance_api_v1_organizations__organization_id__events__event_id__attendance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttendanceMethod
         * @enum {string}
         */
        AttendanceMethod: "QR" | "MANUAL";
        /** AuditRecordResponse */
        AuditRecordResponse: {
            /** Id */
            id: string;
            /** Organization Id */
            organization_id: string | null;
            /** Actor Id */
            actor_id: string | null;
            /** Actor Type */
            actor_type: string;
            /** Action */
            action: string;
            /** Resource Type */
            resource_type: string;
            /** Resource Id */
            resource_id: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Ip Address */
            ip_address: string | null;
            /** User Agent */
            user_agent: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** CampusCreate */
        CampusCreate: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
        };
        /** CampusResponse */
        CampusResponse: {
            /** Id */
            id: string;
            /** Organization Id */
            organization_id: string;
            /** Name */
            name: string;
            /** Address */
            address: string | null;
            /** Status */
            status: string;
        };
        /** DepartmentCreate */
        DepartmentCreate: {
            /** Name */
            name: string;
            /** Code */
            code?: string | null;
            /** Campus Id */
            campus_id?: string | null;
        };
        /** DepartmentResponse */
        DepartmentResponse: {
            /** Id */
            id: string;
            /** Organization Id */
            organization_id: string;
            /** Campus Id */
            campus_id: string | null;
            /** Name */
            name: string;
            /** Code */
            code: string | null;
            /** Status */
            status: string;
        };
        /** EventAttendanceCreate */
        EventAttendanceCreate: {
            /** User Id */
            user_id: string;
            method: components["schemas"]["AttendanceMethod"];
        };
        /** EventAttendanceResponse */
        EventAttendanceResponse: {
            /** Id */
            id: string;
            /** Event Id */
            event_id: string;
            /** Registration Id */
            registration_id: string;
            /** User Id */
            user_id: string;
            /**
             * Checked In At
             * Format: date-time
             */
            checked_in_at: string;
            method: components["schemas"]["AttendanceMethod"];
        };
        /** EventCreate */
        EventCreate: {
            /** Title */
            title: string;
            event_type: components["schemas"]["EventType"];
            /** Venue */
            venue: string;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Capacity */
            capacity: number;
            /** Campus Id */
            campus_id?: string | null;
            /** Department Id */
            department_id?: string | null;
            /** Description */
            description?: string | null;
        };
        /** EventRegistrationResponse */
        EventRegistrationResponse: {
            /** Id */
            id: string;
            /** Event Id */
            event_id: string;
            /** User Id */
            user_id: string;
            status: components["schemas"]["RegistrationStatus"];
            /** Registered At */
            registered_at: string | null;
            /** Cancelled At */
            cancelled_at: string | null;
        };
        /** EventResponse */
        EventResponse: {
            /** Id */
            id: string;
            /** Organization Id */
            organization_id: string;
            /** Title */
            title: string;
            event_type: components["schemas"]["EventType"];
            /** Venue */
            venue: string;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Capacity */
            capacity: number;
            /** Organizer Id */
            organizer_id: string;
            status: components["schemas"]["EventStatus"];
            /** Campus Id */
            campus_id: string | null;
            /** Department Id */
            department_id: string | null;
            /** Description */
            description: string | null;
            /** Workflow Instance Id */
            workflow_instance_id: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * EventStatus
         * @enum {string}
         */
        EventStatus: "DRAFT" | "SUBMITTED" | "APPROVED" | "PUBLISHED" | "ONGOING" | "COMPLETED" | "ARCHIVED";
        /**
         * EventType
         * @enum {string}
         */
        EventType: "WORKSHOP" | "SEMINAR" | "HACKATHON" | "FEST" | "CONFERENCE" | "COMPETITION" | "OTHER";
        /** EventUpdate */
        EventUpdate: {
            /** Title */
            title?: string | null;
            event_type?: components["schemas"]["EventType"] | null;
            /** Venue */
            venue?: string | null;
            /** Start At */
            start_at?: string | null;
            /** End At */
            end_at?: string | null;
            /** Capacity */
            capacity?: number | null;
            /** Campus Id */
            campus_id?: string | null;
            /** Department Id */
            department_id?: string | null;
            /** Description */
            description?: string | null;
        };
        /** ExecuteTransitionRequest */
        ExecuteTransitionRequest: {
            /** Action */
            action: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** OrganizationCreate */
        OrganizationCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
            /**
             * Type
             * @default other
             */
            type: string;
        };
        /** OrganizationResponse */
        OrganizationResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
        };
        /** OrganizationUpdate */
        OrganizationUpdate: {
            /** Name */
            name?: string | null;
            /** Type */
            type?: string | null;
        };
        /** PaginatedAuditResponse */
        PaginatedAuditResponse: {
            /** Items */
            items: components["schemas"]["AuditRecordResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /**
         * RegistrationStatus
         * @enum {string}
         */
        RegistrationStatus: "REGISTERED" | "CANCELLED" | "ATTENDED";
        /** RoleAssign */
        RoleAssign: {
            /**
             * Role Id
             * @description The ID of the role to assign
             */
            role_id: string;
        };
        /** RoleCreate */
        RoleCreate: {
            /**
             * Name
             * @description The name of the role
             */
            name: string;
            /**
             * Description
             * @description Optional description of the role
             */
            description?: string | null;
        };
        /** RoleResponse */
        RoleResponse: {
            /**
             * Name
             * @description The name of the role
             */
            name: string;
            /**
             * Description
             * @description Optional description of the role
             */
            description?: string | null;
            /** Id */
            id: string;
            /** Organization Id */
            organization_id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TokenResponse
         * @description OAuth2-compatible token response.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Access token lifetime in seconds
             */
            expires_in: number;
        };
        /**
         * UserResponse
         * @description Current user details (returned from /auth/me).
         */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowDefinitionCreate */
        WorkflowDefinitionCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** WorkflowDefinitionResponse */
        WorkflowDefinitionResponse: {
            /** Id */
            id: string;
            /** Organization Id */
            organization_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Version */
            version: number;
            status: components["schemas"]["WorkflowDefinitionStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * WorkflowDefinitionStatus
         * @enum {string}
         */
        WorkflowDefinitionStatus: "DRAFT" | "PUBLISHED" | "ARCHIVED";
        /** WorkflowExecutionResponse */
        WorkflowExecutionResponse: {
            /** Id */
            id: string;
            /** Workflow Instance Id */
            workflow_instance_id: string;
            /** Actor Id */
            actor_id: string;
            /** Action */
            action: string;
            /** From State */
            from_state: string | null;
            /** To State */
            to_state: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** WorkflowInstanceResponse */
        WorkflowInstanceResponse: {
            /** Id */
            id: string;
            /** Organization Id */
            organization_id: string;
            /** Workflow Definition Id */
            workflow_definition_id: string;
            /** Current State Id */
            current_state_id: string;
            /** Resource Type */
            resource_type: string;
            /** Resource Id */
            resource_id: string;
            /** Started By */
            started_by: string;
            status: components["schemas"]["WorkflowInstanceStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WorkflowInstanceStart */
        WorkflowInstanceStart: {
            /** Workflow Definition Id */
            workflow_definition_id: string;
            /** Resource Type */
            resource_type: string;
            /** Resource Id */
            resource_id: string;
        };
        /**
         * WorkflowInstanceStatus
         * @enum {string}
         */
        WorkflowInstanceStatus: "ACTIVE" | "COMPLETED" | "CANCELLED";
        /** WorkflowStateCreate */
        WorkflowStateCreate: {
            /** Name */
            name: string;
            /** Key */
            key: string;
            type: components["schemas"]["WorkflowStateType"];
        };
        /** WorkflowStateResponse */
        WorkflowStateResponse: {
            /** Id */
            id: string;
            /** Workflow Definition Id */
            workflow_definition_id: string;
            /** Name */
            name: string;
            /** Key */
            key: string;
            type: components["schemas"]["WorkflowStateType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * WorkflowStateType
         * @enum {string}
         */
        WorkflowStateType: "INITIAL" | "NORMAL" | "FINAL";
        /** WorkflowTaskCreate */
        WorkflowTaskCreate: {
            /** Title */
            title: string;
            /** Assigned User Id */
            assigned_user_id?: string | null;
            /** Assigned Role Id */
            assigned_role_id?: string | null;
            /** Due At */
            due_at?: string | null;
        };
        /** WorkflowTaskResponse */
        WorkflowTaskResponse: {
            /** Id */
            id: string;
            /** Workflow Instance Id */
            workflow_instance_id: string;
            /** Title */
            title: string;
            /** Assigned User Id */
            assigned_user_id: string | null;
            /** Assigned Role Id */
            assigned_role_id: string | null;
            status: components["schemas"]["WorkflowTaskStatus"];
            /** Due At */
            due_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * WorkflowTaskStatus
         * @enum {string}
         */
        WorkflowTaskStatus: "PENDING" | "COMPLETED";
        /** WorkflowTransitionCreate */
        WorkflowTransitionCreate: {
            /** From State Id */
            from_state_id: string;
            /** To State Id */
            to_state_id: string;
            /** Action */
            action: string;
            /** Required Permission */
            required_permission?: string | null;
        };
        /** WorkflowTransitionResponse */
        WorkflowTransitionResponse: {
            /** Id */
            id: string;
            /** Workflow Definition Id */
            workflow_definition_id: string;
            /** From State Id */
            from_state_id: string;
            /** To State Id */
            to_state_id: string;
            /** Action */
            action: string;
            /** Required Permission */
            required_permission: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_liveness_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    create_organization_api_v1_organizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_organizations_api_v1_organizations_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"][];
                };
            };
        };
    };
    get_organization_api_v1_organizations__org_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_organization_api_v1_organizations__org_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_organization_members_api_v1_organizations__org_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_campuses_api_v1_organizations__org_id__campuses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_campus_api_v1_organizations__org_id__campuses_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampusCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_departments_api_v1_organizations__org_id__departments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_department_api_v1_organizations__org_id__departments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_api_v1_organizations__organization_id__roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_role_api_v1_organizations__organization_id__roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_role_api_v1_organizations__organization_id__members__member_user_id__role_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                member_user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAssign"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_logs_api_v1_organizations__organization_id__audit_get: {
        parameters: {
            query?: {
                actor_id?: string | null;
                action?: string | null;
                resource_type?: string | null;
                resource_id?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflow_definitions_api_v1_organizations__organization_id__workflows_definitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workflow_definition_api_v1_organizations__organization_id__workflows_definitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowDefinitionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_definition_api_v1_organizations__organization_id__workflows_definitions__definition_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                definition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_workflow_definition_api_v1_organizations__organization_id__workflows_definitions__definition_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                definition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflow_states_api_v1_organizations__organization_id__workflows_definitions__definition_id__states_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                definition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStateResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_workflow_state_api_v1_organizations__organization_id__workflows_definitions__definition_id__states_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                definition_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowStateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflow_transitions_api_v1_organizations__organization_id__workflows_definitions__definition_id__transitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                definition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowTransitionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_workflow_transition_api_v1_organizations__organization_id__workflows_definitions__definition_id__transitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                definition_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowTransitionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_workflow_instance_api_v1_organizations__organization_id__workflows_instances_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowInstanceStart"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowInstanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_instance_api_v1_organizations__organization_id__workflows_instances__instance_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowInstanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_workflow_transition_api_v1_organizations__organization_id__workflows_instances__instance_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowInstanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_execution_history_api_v1_organizations__organization_id__workflows_instances__instance_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowExecutionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflow_tasks_api_v1_organizations__organization_id__workflows_instances__instance_id__tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowTaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workflow_task_api_v1_organizations__organization_id__workflows_instances__instance_id__tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowTaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_workflow_task_api_v1_organizations__organization_id__workflows_instances__instance_id__tasks__task_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                instance_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_organizations__organization_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_v1_organizations__organization_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_organizations__organization_id__events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_event_api_v1_organizations__organization_id__events__event_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_event_api_v1_organizations__organization_id__events__event_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_event_api_v1_organizations__organization_id__events__event_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_event_api_v1_organizations__organization_id__events__event_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_event_api_v1_organizations__organization_id__events__event_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_event_api_v1_organizations__organization_id__events__event_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_event_api_v1_organizations__organization_id__events__event_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_event_api_v1_organizations__organization_id__events__event_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_event_api_v1_organizations__organization_id__events__event_id__register_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRegistrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_registration_api_v1_organizations__organization_id__events__event_id__register_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRegistrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_registrations_api_v1_organizations__organization_id__events__event_id__registrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRegistrationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attendance_api_v1_organizations__organization_id__events__event_id__attendance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAttendanceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_attendance_api_v1_organizations__organization_id__events__event_id__attendance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventAttendanceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAttendanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
